server:
  port: 8080
  error:
    include-message: always

  datasource:
    username: root
    password: iammanjaro
    url: jdbc:mysql://localhost:3306/mydb

  jpa:
    properties:
      database : mysql
      current_session_context_class : thread
      hibernate-dialect : org.hibernate.dialect.MySQLDialect
      show_sql : true
      format_sql : true
    open-in-view: false

  mvc:
    hidden-method:
      filter:
        enabled: true