#debug: true

server:
  port: 8080
  error:
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include:
          - beans
          - info
          - mappings
          - loggers
          - httptrace
          - metrics
          - health
spring:
  boot:
    admin:
      client:
        url: http://localhost:9090
  info:
    env:
      enabled: true

  datasource:
    username: root
    password: iammanjaro
    url: jdbc:mysql://localhost:3306/mydb

  jpa:
    properties:
      database: mysql
      current_session_context_class: thread
      hibernate-dialect: org.hibernate.dialect.MySQLDialect
      show_sql: true
      format_sql: true
    open-in-view: false

  mvc:
    hidden-method:
      filter:
        enabled: true

bot:
  name: measureAPIbot
  key: 5658858750:AAHuiJ4hKeftKNLY71tTPI2UMLDkpnBjmJM
  boot:

servlet:
  multipart:
    max-file-size: 256KB
    max-request-size: 256KB