server:
  port: 8080
  error:
    include-message: always

spring:
  servlet:
    multipart:
      max-file-size: 256KB
      max-request-size: 256KB

  datasource:
    username: root
    password: test
    url: jdbc:mysql://localhost:3306/mydb

  jpa:
    properties:
      database: mysql
      current_session_context_class: thread
      hibernate-dialect: org.hibernate.dialect.MySQLDialect
      show_sql: true
      format_sql: true
    open-in-view: false

  mvc:
    hidden-method:
      filter:
        enabled: true

debug: true
